# vim: set ft=yaml ts=2 expandtab:
---

# This file is part of ansible-collection-epel
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-openssh is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-openssh is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-openssh.
# If not, see <https://www.gnu.org/licenses/>.

- name: get OS specific variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}.yml"
  - "nomatch.yml"

- name: assertions
  ansible.builtin.assert:
    that:
    - epel_repo_state in [ 'present', 'absent' ]

# do not do it for epel9
# it does not exist yet
#
- name: include_tasks for epel_repo_state
  ansible.builtin.include_tasks: "{{ epel_repo_state }}.yml"
  when:
  - ansible_os_family in ['RedHat', 'Rocky']
  - ansible_distribution != 'Fedora'
  - ansible_distribution_major_version is version('9', '<')

- name: include role for epel_next instead
  include_role:
    name: mafalb.epel.next
  when:
  - ansible_os_family in ['RedHat', 'Rocky']
  - ansible_distribution != 'Fedora'
  - ansible_distribution_major_version is version('9')

...
