# vim: set ft=yaml ts=2 expandtab:
---

- name: converge epel
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - block:

    - name: include mafalb.epel.next_release
      include_role:
        name: mafalb.epel.next_release

...
