# vim: set ft=yaml ts=2 expandtab:
---

- name: converge epel next
  hosts: all,!infrastructure_group
  tasks:
  - name: get eligible nodes for epel-next-release
    group_by:
      key: el{{ ansible_distribution_major_version }}
      parents: el8andnewer
    when:
    - ansible_distribution_major_version is version('8','>=')
    - ansible_distribution != 'Fedora'
    - ansible_os_family == 'RedHat'
    changed_when: false

- name: converge epel next
  hosts: el8andnewer

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - name: include mafalb.epel.next
    include_role:
      name: mafalb.epel.next

...
