# vim: set ft=yaml ts=2 expandtab:
---

- name: verify
  hosts: all,!infrastructure_group,!ci-fedora*

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  - name: powertools is enabled
    ansible.builtin.shell: |
      set -o pipefail
      yum repolist|grep ^powertools
    when:
    - ansible_distribution != 'RedHat'
    - ansible_distribution_major_version is version('8', '>=')
    changed_when: false
    args:
      warn: false
      executable: /bin/bash

  - name: codeready is enabled
    ansible.builtin.shell: |
      set -o pipefail
      yum repolist|grep ^codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms
    when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version is version('8', '>=')
    changed_when: false
    args:
      warn: false
      executable: /bin/bash

  - name: test package install
    ansible.builtin.package:
      name: epel-rpm-macros.noarch

...
