# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - c8s
        - alma8
        - rocky8
        - centos7
        - centos8

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

        include:

        - target: c8s
          distribution: centos
          registry: "quay.io/centos/"
          version: stream8

        - target: alma8
          distribution: almalinux
          registry: "docker.io/almalinux/"
          version: 8

        - target: rocky8
          distribution: rockylinux
          registry: "docker.io/rockylinux/"
          tag: '8'

        - target: centos7
          distribution: centos
          version: 7

        - target: centos8
          distribution: centos
          version: 8

    env:
      
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_REGISTRY: ${{ matrix.registry }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
 
    defaults:
      run:
        working-directory: ansible_collections/mafalb/epel

    steps:

    - name: checkout collection mafalb.epel
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/epel

    # use the github actions ansible
    #
    - name: get mafalb.ansible
      run: ansible-galaxy collection install mafalb.ansible

    - name: install molecule
      run: |
        sudo apt-get install ansible
        /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: molecule tests
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

    - name: molecule tests for epel-next-release
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test -s next-release

...
